name: CI
on: [ push ]
jobs:
  Tests-Running:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.ETHERSCAN_TEST_API_KEY }}
    steps:
      - uses: actions/checkout@v1
      - run: pip install tox
      - run: chmod +x ${GITHUB_WORKSPACE}/run_tests.sh
      - run: ${GITHUB_WORKSPACE}/run_tests.sh $API_KEY